_default:
  just -l

test:
  go test github.com/acheronfail/nxkit/...

testw:
  reflex -r '\.go$' -- just test

bench:
  go test -bench=. github.com/acheronfail/nxkit/...

build:
  go build -o nxkit main.go

run *args:
  rm -rf staging staging.bkp
  mkdir staging staging.bkp
  cp ../vendor/Forwarder-Mod/hbl.npdm staging/main.npdm
  cp ../vendor/Forwarder-Mod/hbl.nso staging/main.nso
  go run main.go {{args}}
  md5sum staging/main.npdm ../vendor/Forwarder-Mod/hbl.npdm
