_default:
  just -l

setup:
  go mod tidy
  go install github.com/cespare/reflex@latest
  just fixtures

fixtures:
  bash ./lib/fat/testdata/create.sh

test n *args: fixtures
  FAT={{n}} go test github.com/acheronfail/nxkit/... {{args}}
  FAT={{n}} go test github.com/acheronfail/nxkit/... {{args}}

testw n *args:
  reflex -d none -sr '\.go$' -- just test {{n}} {{args}}

test-all: fixtures
  FAT=16 go test github.com/acheronfail/nxkit/...
  FAT=16 go test github.com/acheronfail/nxkit/...
  FAT=32 go test github.com/acheronfail/nxkit/...
  FAT=32 go test github.com/acheronfail/nxkit/...

bench:
  go test -bench=. github.com/acheronfail/nxkit/...

build:
  go build -o nxkit main.go

run *args:
  rm -rf staging staging.bkp
  mkdir staging staging.bkp
  cp ../vendor/Forwarder-Mod/hbl.npdm staging/main.npdm
  cp ../vendor/Forwarder-Mod/hbl.nso staging/main.nso
  go run main.go {{args}}
  md5sum staging/main.npdm ../vendor/Forwarder-Mod/hbl.npdm

dev *args:
  reflex -d none -sr '\.go$' -- just run {{args}}
