name: Publish Release
on:
  push:
    # Enable when testing release infrastructure on a branch.
    branches:
      - ci/setup
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  build-release:
    name: build-release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build: [linux-gnu, macos, win-msvc]
        include:
          - build: linux-gnu
            os: ubuntu-latest
          - build: macos
            os: macos-latest
          - build: win-msvc
            os: windows-2022

    steps:
      # checkout
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      # cache
      - uses: actions/cache@v4
        with:
          path: node_modules/
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/package-lock.json') }}

      # install just
      - uses: extractions/setup-just@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # install node
      - uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'

      # install python (node-gyp@<10 has issues with python3.12)
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - if: matrix.os == 'macos-latest'
        run: brew install openssl

      - if: matrix.os == 'windows-2022'
        id: vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          runVcpkgInstall: true
          vcpkgGitCommitId: b02e341c927f16d991edbd915d8ea43eac52096c
      - if: matrix.os == 'windows-2022'
        run: |
          $libssl = Get-ChildItem -Path $vcpkgRoot -Recurse -Filter libssl.lib | Where-Object { $_.FullName -notmatch '\\debug\\' }
          $opensslLibDir = Split-Path -Path $libssl.FullName -Parent
          echo "OPENSSL_LIB_DIR=$opensslLibDir" >> $env:GITHUB_ENV
          Write-Host "OPENSSL_LIB_DIR: $opensslLibDir"

      # dependencies
      - name: Setup Dependencies
        run: just setup

      # test
      - name: Test XTSN
        if: matrix.os == 'windows-2022'
        run: |
          cd src/node/nand/xtsn && npm run build
          npm run test

      - name: Test NXKit
        run: just test-all

      # publish
      - name: Publish
        run: just publish
